# Form implementation generated from reading ui file 'predicao.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem

from tkinter import Tk
from tkinter.filedialog import askopenfilename
import sys
import pandas as pd
from os.path import dirname,realpath,join
import numpy as np
from statsmodels.tsa.ar_model import AutoReg 


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 424)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("financeiro.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgba(85, 170, 255, 200);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnArquivo = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnArquivo.setGeometry(QtCore.QRect(570, 50, 75, 23))
        self.btnArquivo.setObjectName("btnArquivo")
        self.btnPredizer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnPredizer.setGeometry(QtCore.QRect(504, 320, 91, 23))
        self.btnPredizer.setObjectName("btnPredizer")
        self.txt_predicao = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_predicao.setGeometry(QtCore.QRect(10, 320, 481, 31))
        self.txt_predicao.setObjectName("txt_predicao")
        self.lbCredito = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbCredito.setGeometry(QtCore.QRect(380, 360, 161, 20))
        self.lbCredito.setObjectName("lbCredito")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 0, 361, 31))
        self.label_2.setStyleSheet("font: 87 24pt rgb(0, 0, 127) \"Roboto\";")
        self.label_2.setObjectName("label_2")
        self.txt_faturado = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txt_faturado.setGeometry(QtCore.QRect(180, 50, 261, 21))
        self.txt_faturado.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 170, 255);")
        self.txt_faturado.setObjectName("txt_faturado")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 30, 91, 16))
        self.label_3.setObjectName("label_3")
        self.sb_colunas = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.sb_colunas.setGeometry(QtCore.QRect(460, 50, 91, 22))
        self.sb_colunas.setObjectName("sb_colunas")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(500, 110, 151, 151))
        self.groupBox.setObjectName("groupBox")
        self.rbSeriesTemporais = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbSeriesTemporais.setGeometry(QtCore.QRect(10, 120, 111, 21))
        self.rbSeriesTemporais.setObjectName("rbSeriesTemporais")
        self.rbRegressaoLinear = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbRegressaoLinear.setGeometry(QtCore.QRect(10, 100, 121, 18))
        self.rbRegressaoLinear.setObjectName("rbRegressaoLinear")
        self.rbSegregacaoDados = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbSegregacaoDados.setGeometry(QtCore.QRect(10, 80, 131, 18))
        self.rbSegregacaoDados.setObjectName("rbSegregacaoDados")
        self.rbMedia = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbMedia.setGeometry(QtCore.QRect(10, 20, 80, 18))
        self.rbMedia.setChecked(True)
        self.rbMedia.setObjectName("rbMedia")
        self.rbMediaPonderada = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbMediaPonderada.setGeometry(QtCore.QRect(10, 60, 91, 18))
        self.rbMediaPonderada.setObjectName("rbMediaPonderada")
        self.rbDesvioPadrao = QtWidgets.QRadioButton(parent=self.groupBox)
        self.rbDesvioPadrao.setGeometry(QtCore.QRect(10, 40, 91, 18))
        self.rbDesvioPadrao.setObjectName("rbDesvioPadrao")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 80, 481, 231))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        #-------------------------------Ação dos Botoes-----------------------------------------#

        self.btnArquivo.clicked.connect(self.openFile)
        self.btnArquivo.clicked.connect(self.predicao)
    #-------------------------------funçoes dos Botoes-----------------------------------------#
    def openFile(self):
        #localiza o caminho do arquivo
        Tk().withdraw()
        path=askopenfilename()
        self.all_data= pd.read_csv(path)
        #carrega a tabela de faturamento
        numColunm=self.sb_colunas.value()
        if numColunm ==0:
            numrolls=len(self.all_data.index)
        else:
            numrolls=numColunm
            
        self.tableWidget.setColumnCount(len(self.all_data.columns))
        self.tableWidget.setRowCount(numrolls)
        self.tableWidget.setHorizontalHeaderLabels(self.all_data.columns)
        
        for i in range(numrolls):
            for j in range(len(self.all_data.columns)):
                self.tableWidget.setItem(i,j,QTableWidgetItem(str(self.all_data.iat[i,j])))
                
        self.tableWidget.resizeColumnsToContents()
        self.tableWidget.resizeRowsToContents()
        
        #soma do faturamento
        somaFaturamento=str('R$%0.02f'%sum(self.all_data['Faturamento']))
        self.txt_faturado.setText(somaFaturamento)
        
        
            
            
        
    
    def predicao(self):
        pass

#-------------------------------Ação dos Botoes-----------------------------------------#

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Predição de Faturamento"))
        self.btnArquivo.setText(_translate("MainWindow", "Arquivo"))
        self.btnPredizer.setText(_translate("MainWindow", "Predizer"))
        self.lbCredito.setText(_translate("MainWindow", "Desenvolvido por Helio Tome"))
        self.label_2.setText(_translate("MainWindow", "Predição de Faturamento"))
        self.label_3.setText(_translate("MainWindow", "Total Faturado"))
        self.groupBox.setTitle(_translate("MainWindow", "Metricas"))
        self.rbSeriesTemporais.setText(_translate("MainWindow", "Series Temporais"))
        self.rbRegressaoLinear.setText(_translate("MainWindow", "Regressão Linear"))
        self.rbSegregacaoDados.setText(_translate("MainWindow", "Segregação de Dados"))
        self.rbMedia.setText(_translate("MainWindow", "Media"))
        self.rbMediaPonderada.setText(_translate("MainWindow", "Media Ponderada"))
        self.rbDesvioPadrao.setText(_translate("MainWindow", "Desvio Padrão"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ano"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Mes"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Faturamento"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
